package component:kvstore@0.1.0;

world kvstoreworld {
    export types;
}

interface types { 

    record key-value-pair {
        key: string,
        value: string,
    }

    type key = string;

    variant error{
        key-not-found,
        key-already-exists,
        unexpected-error,
        key-overflow-error,
        value-overflow-error,
        try-from-slice-error,
        utf8-error,
        filesystem-error(u8),
        invalid-magic-bytes,
        stream-error
    }
    

    resource kvstore {

        constructor();

        insert: func(kv: key-value-pair) -> result<_, error>;

        search: func(key: key) -> result<key-value-pair, error>;

        delete: func(key: key) -> result<_, error>;

       
    }
}




